import { NextResponse } from "next/server";
import { z } from "zod";
import { getUserId } from "@/lib/auth";
import { db } from "@/lib/db";
import { clientKey, rateLimit } from "@/lib/rate-limit";

// Mirrors db/migrations/0022_consent_log.sql: a missing migration must not be
// the reason a consent goes unrecorded.
const SCHEMA = `CREATE TABLE IF NOT EXISTS consent_log (
  id TEXT PRIMARY KEY,
  choice TEXT NOT NULL,
  policy_version TEXT NOT NULL,
  tags TEXT,
  user_id TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE INDEX IF NOT EXISTS idx_consent_log_time ON consent_log(created_at);
CREATE INDEX IF NOT EXISTS idx_consent_log_user ON consent_log(user_id);`;

const bodySchema = z.object({
  // Generated by the browser and kept in the visitor's own cookie, so their
  // device is the key to their row and we store nothing identifying.
  id: z.string().uuid(),
  choice: z.enum(["granted", "denied", "withdrawn"]),
  policyVersion: z.string().min(1).max(16),
  tags: z.string().max(120).optional(),
});

/**
 * Writes the proof that a choice was made.
 *
 * Article 7 of the GDPR asks the controller to demonstrate consent, which a
 * cookie on the visitor's device cannot do — it can be cleared, and it says
 * nothing about what was on screen at the time. This records the answer, the
 * version of the text that produced it and which third parties it covered.
 */
export async function POST(request: Request) {
  if (!rateLimit(clientKey(request, "consent"), 20, 60 * 60_000).allowed) {
    // A flood is not a reason to argue with the visitor about their cookies.
    return NextResponse.json({ ok: true });
  }

  const parsed = bodySchema.safeParse(await request.json().catch(() => null));
  if (!parsed.success) return NextResponse.json({ error: "Invalid request" }, { status: 400 });
  const { id, choice, policyVersion, tags } = parsed.data;

  // A signed-in choice is the strongest evidence available; an anonymous one
  // is still valid, just linked through the receipt instead.
  const userId = await getUserId().catch(() => null);

  const database = db();
  const insert = () =>
    database.execute({
      // The same receipt arriving twice is a retry, not a second decision.
      sql: "INSERT OR REPLACE INTO consent_log (id, choice, policy_version, tags, user_id) VALUES (?, ?, ?, ?, ?)",
      args: [id, choice, policyVersion, tags ?? null, userId ?? null],
    });

  try {
    await insert();
  } catch {
    try {
      await database.executeMultiple(SCHEMA);
      await insert();
    } catch (error) {
      console.error("consent log failed:", error);
      // The choice already took effect in the browser. Failing here would
      // undo a refusal, which is the one outcome worse than losing the record.
      return NextResponse.json({ ok: true, logged: false });
    }
  }

  return NextResponse.json({ ok: true, logged: true });
}
