/**
 * The dictionary for Four Letters: every word is exactly four letters, and
 * every one carries the Italian it means, because in ExecLingo a word made is
 * a word learned — the end-of-game list is the point, not a scoreboard
 * decoration.
 *
 * Words that share the same letters form a set the game deals together, so a
 * tray often has several right answers, as the original does. Common English
 * first, then the vocabulary of work: someone who plays this on the train
 * should meet words they will actually hear in a meeting.
 */
export type Entry = { word: string; it: string };

export const FOUR_LETTER_WORDS: Entry[] = [
  // ---- anagram families, deliberately kept together ----
  { word: "last", it: "ultimo · durare" },
  { word: "salt", it: "sale" },
  { word: "meat", it: "carne" },
  { word: "team", it: "squadra" },
  { word: "tame", it: "domare · mansueto" },
  { word: "mate", it: "compagno · collega" },
  { word: "item", it: "voce · articolo" },
  { word: "time", it: "tempo · volta" },
  { word: "mite", it: "acaro" },
  { word: "emit", it: "emettere" },
  { word: "note", it: "nota · appunto" },
  { word: "tone", it: "tono" },
  { word: "rate", it: "tasso · tariffa" },
  { word: "tear", it: "lacrima · strappare" },
  { word: "care", it: "cura · importare" },
  { word: "race", it: "gara · corsa" },
  { word: "acre", it: "acro" },
  { word: "deal", it: "affare · accordo" },
  { word: "lead", it: "guidare · contatto commerciale" },
  { word: "lane", it: "corsia · vicolo" },
  { word: "lean", it: "snello · appoggiarsi" },
  { word: "earn", it: "guadagnare" },
  { word: "near", it: "vicino" },
  { word: "gain", it: "guadagno · ottenere" },
  { word: "sale", it: "vendita" },
  { word: "seal", it: "sigillo · foca" },
  { word: "cost", it: "costo · costare" },
  { word: "post", it: "posta · incarico" },
  { word: "spot", it: "punto · individuare" },
  { word: "stop", it: "fermare · fermata" },
  { word: "opts", it: "sceglie" },
  { word: "tops", it: "cime · superare" },
  { word: "pots", it: "pentole" },
  { word: "form", it: "modulo · forma" },
  { word: "from", it: "da" },
  { word: "risk", it: "rischio" },
  { word: "irks", it: "infastidisce" },
  { word: "read", it: "leggere" },
  { word: "dear", it: "caro · gentile" },
  { word: "dare", it: "osare" },
  { word: "hire", it: "assumere · noleggiare" },
  { word: "heir", it: "erede" },
  { word: "fire", it: "fuoco · licenziare" },
  { word: "rife", it: "diffuso" },
  { word: "unit", it: "unità" },
  { word: "sign", it: "firmare · segno" },
  { word: "sing", it: "cantare" },
  { word: "want", it: "volere" },
  { word: "cash", it: "contanti" },
  { word: "loan", it: "prestito" },

  // ---- the vocabulary of work ----
  { word: "bill", it: "conto · fattura" },
  { word: "bank", it: "banca" },
  { word: "bond", it: "obbligazione · legame" },
  { word: "boss", it: "capo" },
  { word: "call", it: "chiamata · chiamare" },
  { word: "card", it: "carta · tessera" },
  { word: "case", it: "caso · pratica" },
  { word: "cell", it: "cella · cellula" },
  { word: "chat", it: "chiacchierata" },
  { word: "chef", it: "cuoco" },
  { word: "chip", it: "chip · scheggia" },
  { word: "club", it: "circolo" },
  { word: "code", it: "codice" },
  { word: "coin", it: "moneta" },
  { word: "cope", it: "farcela · reggere" },
  { word: "core", it: "nucleo · essenziale" },
  { word: "crew", it: "equipaggio · squadra" },
  { word: "crop", it: "raccolto · ritagliare" },
  { word: "data", it: "dati" },
  { word: "date", it: "data · appuntamento" },
  { word: "debt", it: "debito" },
  { word: "desk", it: "scrivania · sportello" },
  { word: "dial", it: "comporre un numero" },
  { word: "does", it: "fa" },
  { word: "down", it: "giù · in calo" },
  { word: "draw", it: "disegnare · attingere · pareggio" },
  { word: "drop", it: "calo · lasciar cadere" },
  { word: "duty", it: "dovere · dazio" },
  { word: "edge", it: "bordo · vantaggio" },
  { word: "exit", it: "uscita · uscire" },
  { word: "fact", it: "fatto" },
  { word: "fail", it: "fallire" },
  { word: "fair", it: "fiera · equo" },
  { word: "fast", it: "veloce" },
  { word: "fees", it: "compensi · commissioni" },
  { word: "file", it: "file · archiviare" },
  { word: "fill", it: "riempire" },
  { word: "firm", it: "azienda · fermo" },
  { word: "flat", it: "piatto · appartamento" },
  { word: "flow", it: "flusso" },
  { word: "fold", it: "piegare" },
  { word: "fund", it: "fondo · finanziare" },
  { word: "gate", it: "cancello · gate" },
  { word: "goal", it: "obiettivo" },
  { word: "gold", it: "oro" },
  { word: "grow", it: "crescere" },
  { word: "half", it: "metà" },
  { word: "hall", it: "sala · ingresso" },
  { word: "hand", it: "mano · consegnare" },
  { word: "head", it: "testa · responsabile" },
  { word: "help", it: "aiuto · aiutare" },
  { word: "high", it: "alto" },
  { word: "hold", it: "tenere · attesa" },
  { word: "host", it: "ospitare · ospite" },
  { word: "hour", it: "ora" },
  { word: "idea", it: "idea" },
  { word: "join", it: "unirsi · entrare" },
  { word: "keep", it: "tenere" },
  { word: "keys", it: "chiavi" },
  { word: "kind", it: "gentile · tipo" },
  { word: "know", it: "sapere · conoscere" },
  { word: "land", it: "terreno · atterrare" },
  { word: "late", it: "tardi · in ritardo" },
  { word: "less", it: "meno" },
  { word: "line", it: "linea · riga" },
  { word: "link", it: "collegamento" },
  { word: "list", it: "elenco" },
  { word: "live", it: "vivere · dal vivo" },
  { word: "lock", it: "serratura · bloccare" },
  { word: "long", it: "lungo" },
  { word: "look", it: "guardare" },
  { word: "loss", it: "perdita" },
  { word: "made", it: "fatto" },
  { word: "mail", it: "posta" },
  { word: "main", it: "principale" },
  { word: "make", it: "fare" },
  { word: "mark", it: "segno · voto" },
  { word: "mass", it: "massa" },
  { word: "meet", it: "incontrare" },
  { word: "mind", it: "mente · dispiacersi" },
  { word: "miss", it: "mancare · perdere" },
  { word: "mode", it: "modalità" },
  { word: "move", it: "muovere · mossa" },
  { word: "must", it: "dovere" },
  { word: "name", it: "nome" },
  { word: "need", it: "bisogno · avere bisogno" },
  { word: "news", it: "notizie" },
  { word: "next", it: "prossimo" },
  { word: "open", it: "aprire · aperto" },
  { word: "page", it: "pagina" },
  { word: "paid", it: "pagato" },
  { word: "pace", it: "ritmo · passo" },
  { word: "pack", it: "pacco · fare le valigie" },
  { word: "part", it: "parte" },
  { word: "pass", it: "passare · superare" },
  { word: "past", it: "passato" },
  { word: "path", it: "percorso" },
  { word: "plan", it: "piano · pianificare" },
  { word: "play", it: "giocare · riprodurre" },
  { word: "plot", it: "trama · tracciare" },
  { word: "plus", it: "più" },
  { word: "pool", it: "fondo comune · piscina" },
  { word: "poor", it: "povero · scarso" },
  { word: "port", it: "porto" },
  { word: "push", it: "spingere" },
  { word: "quit", it: "lasciare · dimettersi" },
  { word: "rank", it: "grado · classificare" },
  { word: "rely", it: "contare su" },
  { word: "rent", it: "affitto · affittare" },
  { word: "rest", it: "riposo · il resto" },
  { word: "rich", it: "ricco" },
  { word: "ride", it: "corsa · viaggiare" },
  { word: "ring", it: "anello · squillare" },
  { word: "rise", it: "salire · aumento" },
  { word: "road", it: "strada" },
  { word: "role", it: "ruolo" },
  { word: "room", it: "stanza · spazio" },
  { word: "rule", it: "regola · governare" },
  { word: "safe", it: "sicuro · cassaforte" },
  { word: "save", it: "salvare · risparmiare" },
  { word: "seat", it: "posto · sedile" },
  { word: "seek", it: "cercare" },
  { word: "sell", it: "vendere" },
  { word: "send", it: "mandare" },
  { word: "ship", it: "nave · spedire" },
  { word: "shop", it: "negozio" },
  { word: "show", it: "mostrare" },
  { word: "side", it: "lato · parte" },
  { word: "site", it: "sito · cantiere" },
  { word: "size", it: "dimensione · taglia" },
  { word: "skip", it: "saltare" },
  { word: "slot", it: "fascia oraria · fessura" },
  { word: "slow", it: "lento" },
  { word: "sold", it: "venduto" },
  { word: "sort", it: "tipo · ordinare" },
  { word: "span", it: "arco · estendersi" },
  { word: "stay", it: "restare · soggiorno" },
  { word: "step", it: "passo · gradino" },
  { word: "such", it: "tale" },
  { word: "sure", it: "sicuro · certo" },
  { word: "swap", it: "scambio · scambiare" },
  { word: "take", it: "prendere" },
  { word: "talk", it: "parlare · discorso" },
  { word: "task", it: "compito" },
  { word: "tell", it: "dire · raccontare" },
  { word: "term", it: "termine · condizione" },
  { word: "test", it: "prova · provare" },
  { word: "text", it: "testo" },
  { word: "than", it: "di · che (nei paragoni)" },
  { word: "then", it: "poi · allora" },
  { word: "tick", it: "spunta · ticchettio" },
  { word: "tier", it: "fascia · livello" },
  { word: "tips", it: "consigli · mance" },
  { word: "tool", it: "strumento" },
  { word: "tour", it: "giro · tournée" },
  { word: "town", it: "città" },
  { word: "trip", it: "viaggio · trasferta" },
  { word: "true", it: "vero" },
  { word: "turn", it: "girare · turno" },
  { word: "type", it: "tipo · digitare" },
  { word: "used", it: "usato" },
  { word: "user", it: "utente" },
  { word: "vast", it: "vasto" },
  { word: "view", it: "vista · opinione" },
  { word: "vote", it: "voto · votare" },
  { word: "wage", it: "salario" },
  { word: "wait", it: "aspettare" },
  { word: "walk", it: "camminare" },
  { word: "wall", it: "muro" },
  { word: "warm", it: "caldo · cordiale" },
  { word: "wave", it: "onda · salutare" },
  { word: "weak", it: "debole" },
  { word: "wear", it: "indossare · usura" },
  { word: "week", it: "settimana" },
  { word: "well", it: "bene · pozzo" },
  { word: "west", it: "ovest" },
  { word: "wide", it: "largo · ampio" },
  { word: "wire", it: "filo · bonifico" },
  { word: "wise", it: "saggio" },
  { word: "wish", it: "desiderio · augurare" },
  { word: "with", it: "con" },
  { word: "word", it: "parola" },
  { word: "work", it: "lavoro · funzionare" },
  { word: "year", it: "anno" },
  { word: "your", it: "tuo · vostro" },
  { word: "zone", it: "zona" },
];
