import { FOUR_LETTER_WORDS, type Entry } from "./four-letters-words";

/**
 * Word ↔ meaning pairs, for every game that asks "what does this mean?".
 *
 * The four-letter list is already a glossary, so it is reused rather than
 * retyped; these are the longer words of working English that a four-letter
 * game can never reach. Glosses are short on purpose: they have to fit on a
 * button next to two others.
 */
const LONGER: Entry[] = [
  { word: "agenda", it: "ordine del giorno" },
  { word: "budget", it: "budget · bilancio previsto" },
  { word: "deadline", it: "scadenza" },
  { word: "invoice", it: "fattura" },
  { word: "meeting", it: "riunione" },
  { word: "revenue", it: "fatturato" },
  { word: "forecast", it: "previsione" },
  { word: "quarter", it: "trimestre" },
  { word: "target", it: "obiettivo" },
  { word: "supplier", it: "fornitore" },
  { word: "customer", it: "cliente" },
  { word: "contract", it: "contratto" },
  { word: "leverage", it: "leva · forza contrattuale" },
  { word: "handover", it: "passaggio di consegne" },
  { word: "shortlist", it: "rosa dei candidati" },
  { word: "feedback", it: "riscontro" },
  { word: "briefing", it: "riunione di allineamento" },
  { word: "pipeline", it: "trattative in corso" },
  { word: "colleague", it: "collega" },
  { word: "audit", it: "revisione contabile" },
  { word: "trainee", it: "tirocinante" },
  { word: "outsource", it: "esternalizzare" },
  { word: "workload", it: "carico di lavoro" },
  { word: "milestone", it: "tappa di progetto" },
  { word: "rollout", it: "lancio progressivo" },
  { word: "turnover", it: "ricambio del personale" },
  { word: "appraisal", it: "valutazione del personale" },
  { word: "headcount", it: "organico" },
  { word: "overhead", it: "costi di struttura" },
  { word: "margin", it: "margine" },
  { word: "discount", it: "sconto" },
  { word: "deliver", it: "consegnare" },
  { word: "negotiate", it: "trattare" },
  { word: "postpone", it: "rinviare" },
  { word: "approve", it: "approvare" },
  { word: "attend", it: "partecipare" },
  { word: "commute", it: "spostarsi casa-lavoro" },
  { word: "expense", it: "spesa aziendale" },
  { word: "receipt", it: "ricevuta" },
  { word: "schedule", it: "calendario · programmare" },
  { word: "shipment", it: "spedizione" },
  { word: "warehouse", it: "magazzino" },
  { word: "insurance", it: "assicurazione" },
  { word: "liability", it: "responsabilità · passività" },
  { word: "breakdown", it: "dettaglio voce per voce" },
  { word: "highlight", it: "mettere in evidenza" },
  { word: "outcome", it: "esito" },
  { word: "agreement", it: "accordo" },
  { word: "proposal", it: "proposta" },
  { word: "reminder", it: "sollecito" },
  { word: "achieve", it: "raggiungere" },
  { word: "advise", it: "consigliare" },
  { word: "afford", it: "permettersi" },
  { word: "assess", it: "valutare" },
  { word: "assign", it: "assegnare" },
  { word: "attempt", it: "tentativo · tentare" },
  { word: "available", it: "disponibile" },
  { word: "average", it: "media" },
  { word: "backlog", it: "arretrato" },
  { word: "benefit", it: "vantaggio" },
  { word: "bottleneck", it: "collo di bottiglia" },
  { word: "chairman", it: "presidente" },
  { word: "commitment", it: "impegno" },
  { word: "competitor", it: "concorrente" },
  { word: "concern", it: "preoccupazione" },
  { word: "deadlock", it: "situazione di stallo" },
  { word: "delay", it: "ritardo" },
  { word: "delegate", it: "delegare" },
  { word: "estimate", it: "stima · preventivo" },
  { word: "figures", it: "numeri · cifre" },
  { word: "handle", it: "gestire" },
  { word: "improve", it: "migliorare" },
  { word: "increase", it: "aumento · aumentare" },
  { word: "issue", it: "problema · questione" },
  { word: "launch", it: "lancio · lanciare" },
  { word: "notice", it: "preavviso · accorgersi" },
  { word: "outstanding", it: "in sospeso · eccellente" },
  { word: "overtime", it: "straordinario" },
  { word: "purchase", it: "acquisto · acquistare" },
  { word: "quote", it: "preventivo · citare" },
  { word: "refund", it: "rimborso" },
  { word: "reliable", it: "affidabile" },
  { word: "require", it: "richiedere" },
  { word: "shareholder", it: "azionista" },
  { word: "spreadsheet", it: "foglio di calcolo" },
  { word: "statement", it: "dichiarazione · estratto conto" },
  { word: "threshold", it: "soglia" },
  { word: "timeline", it: "cronoprogramma" },
  { word: "update", it: "aggiornamento · aggiornare" },
  { word: "vendor", it: "fornitore · venditore" },
  { word: "workflow", it: "flusso di lavoro" },
];

export const GLOSSARY: Entry[] = [...FOUR_LETTER_WORDS, ...LONGER];
export type { Entry };
